---

- name: stone_touched fact is initially false
  set_fact:
    stone_touched: False

- name: Input expectations are verified
  assert:
    that:
      - 'hostvars.localhost.ansible_machine_id | default("", True) | trim | length'
      - 'stone_touched == False'  # make sure it's not read-only
      - 'touchstone_filepath | default("", True) | trim | length'
      - 'touch_touchstone | default(False) in [True, False]'
      - '"{{ role_path }}/files/touchstone.py" | is_file'

- name: Touchstone script command-line arguments are initialized
  set_fact:
    result: 'touchstone.py'

- name: Touchstone script command-line has --touch appended
  set_fact:
    result: '{{ result }} --touch'
  when: touch_touchstone | default(False)

- name: Touchstone script command-line has complete touchstone_filepath appended
  set_fact:
    result: '{{ result }} {{ touchstone_filepath }}/.{{ stone_name }}.touchstone'

- name: Touchstone script command-line has content lines appended
  set_fact:
    result: '{{ result }} {{ item | quote }}'
  when: touch_touchstone | default(False)
  with_items:
    - 'Touched by {{ hostvars.localhost.ansible_nodename }}'
    - 'Machine_id {{ hostvars.localhost.ansible_machine_id }}'
    - 'On {{ hostvars.localhost.ansible_date_time.iso8601 }}'

- name: Touchstone script is executed to modify and/or retrieve stone status
  script: '{{ result }}'
  changed_when: touch_touchstone and
                result.stdout | trim | lower == "true" and
                result.stderr | trim == ''
  register: result

- name: Script output expectations are verified
  assert:
    that: 'result.stdout | trim | lower in ["true","false"]'

- name: Touchstone result is converted into boolean
  set_fact:
    stone_touched: '{{ result.stdout | trim | lower == "true" }}'

- name: Touchstone variables are debugged
  debug:
    var: '{{ item }}'
  with_items:
    - stone_name
    - stone_touched
    - result.stderr
