---

- name: Input expectations are verified
  assert:
    that:
      - 'touchstone_filepath | default("", True) | trim | length'
      - 'touch_touchstone | default(False) | bool in [True, False]'
      - 'touchstone_template | is_file'

- name: The touchstone file path on target is debugged
  debug: msg='{{ touchstone_filepath }}/.{{ stone_name }}.touchstone'

- name: The stone was not touched, unless prooven otherwise.
  set_fact:
    stone_touched: false

- name: Script tasks only run outside of --check mode
  block:

    - name: Touchstone script is executed to set and/or retrieve stone status
      script: >
        touchstone.py \
        {{ "--touch" if touch_touchstone | bool else "" }} \
        {{ touchstone_filepath }}/.{{ stone_name }}.touchstone \
        {% for line in lookup("template", touchstone_template).splitlines() %} \
            {{ line | quote }} \
        {% endfor %}
      # N/B: The script module combines stderr/stdout from the script
      changed_when:
                    touch_touchstone | bool and
                    result.stdout_lines[0] | trim | bool and
                    result.stdout_lines | length == 1
      register: result

    - name: The stone is/was touched, set stone_touched fact True
      set_fact:
        stone_touched: True
      when: result.stdout_lines[0] | trim | bool

  when: not ansible_check_mode | default(False) | bool
